site_name: Chopsticks

theme:
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  name: null
  custom_dir: material
  palette:
    scheme: rubble
  font: false
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - tabs.changeicon
    - toc.autohide
    - colors
  icons:
    _basis: custom/java1
  
  colors:
    default: /#393333
    home: /#666666
    _algorithm: /#088e11

  icon:
    logo: custom/light-bulb
  favicon: assets/t.svg

extra_css:
  - css/general.css
  - css/fonts.css
  - css/code-admonition.css
  - css/katex.css
  - css/tables.css
  - css/extra/admonitions.css
  - css/extra/code-blocks.css
  - css/gadgets/book.css
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.css'

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/contrib/auto-render.min.js'
  - 'js/mkmain.js'
  - 'js/katex.js'

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ⏳
      toc_depth: 6 # Define the range of levels to be included in the table of contents
  - meta

plugins:
  - search

variables:
  - containers:
    - container_path: &container _basis/_containers/
    - api_path: &container_api_path _basis/_containers/_apis/
  - basis: &basis _basis/_basis/
  - miscellaneous: &misc _basis/_misc/

nav:
  - home: index.md
  - Basis⏳:
      - Preface: _basis/index.md 
      - Basis:
        - compound type: _basis/_basis/compound_type.md
        - type: _basis/_basis/type.md
        - list inilization: !!python/object/apply:os.path.join [*basis, list_init.md]
      # - 1. primitive types: _basis/primitive_type.md
      - Containers:
        - 1. sequential container: !!python/object/apply:os.path.join [*container, sequence.md]
        - apis:
            - seq api: !!python/object/apply:os.path.join [*container_api_path, seq_api.md]
      - Smart Pointers:
        - 1: _basis/_smart_pointers/ptr1.md
      - Copy Control:
        - constructor: _basis/_oop/constructor.md
        - copy control: _basis/_oop/copy_control1.md 
      - MISC:
        - copy elision &#58; rvo/nrvo: !!python/object/apply:os.path.join [*misc, rvo_nrvo.md]